<?php
/**
 * Created by PhpStorm.
 * User: DIGITAL
 * Date: 28/03/2019
 * Time: 10:17
 */

namespace YamiTec\Controllers;


use YamiTec\Handlers\YamitecHandler;

class HomeController extends YamitecHandler
{
    public function construct($config = [])
    {
        $config = [
            "inRoutes"=> ["home" => "app\Controllers\HomeController"],
            "Routes" => ["home" => "app\Controllers\HomeController"],
        ];
        parent::construct($config); // TODO: Change the autogenerated stub
    }
}